/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_broadcom_bt_app_fm_service_FmReceiverService */

#ifndef _Included_com_broadcom_bt_app_fm_service_FmReceiverService
#define _Included_com_broadcom_bt_app_fm_service_FmReceiverService
#ifdef __cplusplus
extern "C" {
#endif
#undef com_broadcom_bt_app_fm_service_FmReceiverService_V
#define com_broadcom_bt_app_fm_service_FmReceiverService_V 1L
/*
 * Class:     com_broadcom_bt_app_fm_service_FmReceiverService
 * Method:    classFmInitNative
 * Signature: ()V
 */
JNIEXPORT static void JNICALL Java_com_broadcom_bt_app_fm_service_FmReceiverService_classFmInitNative
  (JNIEnv *, jclass);

/*
 * Class:     com_broadcom_bt_app_fm_service_FmReceiverService
 * Method:    initLoopNative
 * Signature: ()V
 */
JNIEXPORT static void JNICALL Java_com_broadcom_bt_app_fm_service_FmReceiverService_initLoopNative
  (JNIEnv *, jobject);

/*
 * Class:     com_broadcom_bt_app_fm_service_FmReceiverService
 * Method:    cleanupLoopNative
 * Signature: ()V
 */
JNIEXPORT static void JNICALL Java_com_broadcom_bt_app_fm_service_FmReceiverService_cleanupLoopNative
  (JNIEnv *, jobject);

/*
 * Class:     com_broadcom_bt_app_fm_service_FmReceiverService
 * Method:    initNativeDataNative
 * Signature: ()V
 */
JNIEXPORT static void JNICALL Java_com_broadcom_bt_app_fm_service_FmReceiverService_initNativeDataNative
  (JNIEnv *, jobject);

/*
 * Class:     com_broadcom_bt_app_fm_service_FmReceiverService
 * Method:    enableNative
 * Signature: (I)Z
 */
JNIEXPORT static jboolean JNICALL Java_com_broadcom_bt_app_fm_service_FmReceiverService_enableNative
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_broadcom_bt_app_fm_service_FmReceiverService
 * Method:    disableNative
 * Signature: (Z)Z
 */
JNIEXPORT static jboolean JNICALL Java_com_broadcom_bt_app_fm_service_FmReceiverService_disableNative
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     com_broadcom_bt_app_fm_service_FmReceiverService
 * Method:    tuneNative
 * Signature: (I)Z
 */
JNIEXPORT static jboolean JNICALL Java_com_broadcom_bt_app_fm_service_FmReceiverService_tuneNative
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_broadcom_bt_app_fm_service_FmReceiverService
 * Method:    muteNative
 * Signature: (Z)Z
 */
JNIEXPORT static jboolean JNICALL Java_com_broadcom_bt_app_fm_service_FmReceiverService_muteNative
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     com_broadcom_bt_app_fm_service_FmReceiverService
 * Method:    searchNative
 * Signature: (IIII)Z
 */
JNIEXPORT static jboolean JNICALL Java_com_broadcom_bt_app_fm_service_FmReceiverService_searchNative
  (JNIEnv *, jobject, jint, jint, jint, jint);

/*
 * Class:     com_broadcom_bt_app_fm_service_FmReceiverService
 * Method:    comboSearchNative
 * Signature: (IIIIIZII)Z
 */
JNIEXPORT static jboolean JNICALL Java_com_broadcom_bt_app_fm_service_FmReceiverService_comboSearchNative
  (JNIEnv *, jobject, jint, jint, jint, jint, jint, jboolean, jint, jint);

/*
 * Class:     com_broadcom_bt_app_fm_service_FmReceiverService
 * Method:    searchAbortNative
 * Signature: ()Z
 */
JNIEXPORT static jboolean JNICALL Java_com_broadcom_bt_app_fm_service_FmReceiverService_searchAbortNative
  (JNIEnv *, jobject);

/*
 * Class:     com_broadcom_bt_app_fm_service_FmReceiverService
 * Method:    setRdsModeNative
 * Signature: (ZZI)Z
 */
JNIEXPORT static jboolean JNICALL Java_com_broadcom_bt_app_fm_service_FmReceiverService_setRdsModeNative
  (JNIEnv *, jobject, jboolean, jboolean, jint);

/*
 * Class:     com_broadcom_bt_app_fm_service_FmReceiverService
 * Method:    setAudioModeNative
 * Signature: (I)Z
 */
JNIEXPORT static jboolean JNICALL Java_com_broadcom_bt_app_fm_service_FmReceiverService_setAudioModeNative
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_broadcom_bt_app_fm_service_FmReceiverService
 * Method:    setAudioPathNative
 * Signature: (I)Z
 */
JNIEXPORT static jboolean JNICALL Java_com_broadcom_bt_app_fm_service_FmReceiverService_setAudioPathNative
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_broadcom_bt_app_fm_service_FmReceiverService
 * Method:    setScanStepNative
 * Signature: (I)Z
 */
JNIEXPORT static jboolean JNICALL Java_com_broadcom_bt_app_fm_service_FmReceiverService_setScanStepNative
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_broadcom_bt_app_fm_service_FmReceiverService
 * Method:    setFMVolumeNative
 * Signature: (I)Z
 */
JNIEXPORT static jboolean JNICALL Java_com_broadcom_bt_app_fm_service_FmReceiverService_setFMVolumeNative
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_broadcom_bt_app_fm_service_FmReceiverService
 * Method:    setRegionNative
 * Signature: (I)Z
 */
JNIEXPORT static jboolean JNICALL Java_com_broadcom_bt_app_fm_service_FmReceiverService_setRegionNative
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_broadcom_bt_app_fm_service_FmReceiverService
 * Method:    configureDeemphasisNative
 * Signature: (I)Z
 */
JNIEXPORT static jboolean JNICALL Java_com_broadcom_bt_app_fm_service_FmReceiverService_configureDeemphasisNative
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_broadcom_bt_app_fm_service_FmReceiverService
 * Method:    estimateNoiseFloorNative
 * Signature: (I)Z
 */
JNIEXPORT static jboolean JNICALL Java_com_broadcom_bt_app_fm_service_FmReceiverService_estimateNoiseFloorNative
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_broadcom_bt_app_fm_service_FmReceiverService
 * Method:    getAudioQualityNative
 * Signature: (Z)Z
 */
JNIEXPORT static jboolean JNICALL Java_com_broadcom_bt_app_fm_service_FmReceiverService_getAudioQualityNative
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     com_broadcom_bt_app_fm_service_FmReceiverService
 * Method:    configureSignalNotificationNative
 * Signature: (I)Z
 */
JNIEXPORT static jboolean JNICALL Java_com_broadcom_bt_app_fm_service_FmReceiverService_configureSignalNotificationNative
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
